name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Use Node.js
      - run: make install
      - run: make lint
      - run: make test
      - uses: paambaati/codeclimate-action@v3.0.0
        name: Test & publish code coverage
        env:
          CC_TEST_REPORTER_ID : ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage